[project]
name = "clipit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.3.0",
    "optimum>=1.23.3",
    "transformers>=4.48.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.2",
]
